app/g.go
filter/contentfilter.go

[fix:](https://github.com/Equationzhao/g/commit/94049f996ea0ca722eb348e00905438d9e19b177) 
fix displaying header multi times when there is more than one path args
enhancement:
add the checksum type(s) in header
[fix typo](https://github.com/Equationzhao/g/commit/573c69075bef959b62aecd3c365fc37caa9ec70d)

Fix multi header

---

app/g.go
filter/contentfilter.go
filter/typefliter.go
osbased/filedetail_darwin.go
osbased/filedetail_linux.go
osbased/filedetail_windows.go
osbased/inode_windows.go
sorter/sort.go

feat:
support list each file's number of hard links with flag "link"/"H" support multi time-type "time-type"
support quote/literal "Q"/"N"
support classic mode(no colours or icons) "classic" support show hidden file/dir only "show-only-hidden" support sort=nature(default)
support sort by width
new flag to sort by size/no sort/sort by ext/width
alias long=l/all
alias numeric-uid-gid=numeric
alias permission/perm=show-perm
alias total-size=show-total-size
alias D=show-only-dir

new minor version

---

app/g.go
filter/contentfilter.go

--statistic only works with --total-size

---

app/display.go
app/g.go
app/view.go
display/printer.go
filter/content/duplicate.go
filter/content/name.go

flag to select table style(ascii/unicode)
-format= for more alternatives
show items' name relative to a given path
support footer in tb view
fix:
fix header

feat && bug fix

---

app/g.go

fix 42-footer-alignment

---

app/g.go
render/renderer.go
theme/default.go
theme/default.json

- add custom directory prompt support ( inspired by acarl005/ls-go)
- fix not displaying icon or color correctly when using -fullpath or -relative-path

# new minor version

---

theme/custom_builtin.json
theme/defaultini.go

feat: :sparkles: update custom_builtin

---

render/renderer.go

the color of dir should  not be changed even when it matches the Special names

fix: :bug: fix dir color

---

theme/default.go

add package.json
add tsconfig.json
add go.mod go.sum
add .pages
add .cjs .mjs
add .astro

feat: :lipstick: new style

---

theme/colorless.go

the icon will be displayed correctly when option --colorless is set

fix: :bug: fix colorless icon

---

filter/content/name.go
render/renderer.go
theme/default.go

with its target file type
and
feat: :sparkles: introduce device&char device

feat: :sparkles: colorize the symlink

---

app/g.go
filter/content/name.go

add quotes when the name contains spaces

feat: :sparkles: quote when containing space

---

filter/content/name.go

fix: :bug: fix link arrow style

---

render/renderer.go

fix setgid permission's position

fix: :bug: fix permission

---

theme/custom_builtin.json
theme/default.go
theme/default.json

nix
asc
tf
env
ics
iml
pl
rubydoc
styl
flake.nix
jenkinsfile
brewfile
vagrantfile

feat: :lipstick: new styles

---

filter/content/name.go
theme/color.go
util/util.go

- feat: :sparkles: render the escape char
- fix: :bug: fix auto-quote for other space char

feat: ✨ render the escape char

---

align/left.go
app/g.go
app/view.go
filter/content/git.go
git/git.go
render/renderer.go
theme/default.go
util/set.go

- feat: :sparkles: support custom align
- feat: :sparkles: support repo-branch/repo-status

feat: :sparkles: support repo-branch/repo-status

---

sorter/sort.go

- perf: :zap: improve recursive-size sort prof
- fix: :bug: fix last commit

perf: :zap: improve recursive-size sort prof

---

filter/content/permission.go
go.mod
go.sum

If the file or directory has extended attributes, the permissions field is followed by a '@' character

feat: :sparkles: support @ after permission

---

app/view.go
render/renderer.go
theme/default.go

- fix: :bug: rearrange the --link field
- fix: :bug: fix the link color

fix: :bug: fix link color and rearrange order

---

internal/cli/g.go
internal/const/const.go
internal/display/printer.go
internal/filter/content/name.go
internal/render/renderer.go
internal/theme/color.go
internal/theme/colorless.go
internal/theme/default.go
internal/theme/sys_linux.go
internal/theme/theme.go
internal/theme/theme_test.go
internal/util/file.go
internal/util/util.go

util will import internal/const only

refactor: :recycle: improve import chain

---

internal/theme/custom_builtin.json
internal/theme/default.go
internal/theme/default.json

style: :lipstick: add new style

---

internal/cli/g.go
internal/cli/view.go
internal/content/flags.go
internal/content/name.go
internal/global/const.go
internal/osbased/flags_darwin.go
internal/osbased/flags_linux.go
internal/osbased/flags_windows.go

- **feat: :sparkles: add funcs to get file flags**
- **feat: :sparkles: add flags Enabler**
- **feat: :sparkles: support listing file flags**

feat: :sparkles: support listing file flags

---

.github/workflows/go.yml
internal/osbased/time_linux_64.go
justfile

- **build(ci): :construction_worker: update just aur**
- **feat: :alembic: try loong64**

feat: :alembic: try loong64

---

README.md

- Added badges for GitHub stars, forks, issues, and license

docs: 📝 Update README.md

---

CONTRIBUTING.md
internal/content/contentfilter.go
internal/content/name.go
internal/content/time.go
internal/display/printer.go
internal/render/renderer.go
internal/sorter/sort.go
internal/theme/theme.go
internal/util/util.go
justfile
main.go

- **style: update gofumpt command to include --extra option**
- **use gofumpt --extra rule**

style: format with gofumpt --extra rule

---

internal/cli/g.go

set default style to 'Jan 02 15:04'

fix(cli): update time format for better readability

---

internal/theme/custom_builtin.json
internal/theme/default.go
internal/theme/default.json
internal/util/file.go

- **feat(theme): add new styles for additional file types**
- **refactor(util): remove unused GenRandomData function**
- **fix(theme): correct icon string format for astro style**
- **feat(theme): update theme files**

feat(theme): add new styles for additional file types
